# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8e470ebb75bf056bb144ceee8fd9444fade35030e65d349f532cadd7679e3887c3eac8e72a78e249c7213afb3a4f272f67d517ccc8b2691b568f749257a9b89

test:
  secret_key_base: ddfa837856ba4d4ac10e8c144787eb2ad8e86d17b6951b8f459af1c80abf18188c085039dd80ce2b236eb6e06562c5bb3936b7138635d7fab4c0680ffdf0c749

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
